# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d51327c68be7c197bca6b0131e9f9a2a472b98e4025243153e021b168bceb2f0fd99acaea7b5b49f47870d4058107c9f679c459ec10fae42a77fbcf2956c6094

test:
  secret_key_base: 208d568600e5d2f771a6bff65338a91bb2e02d12644c6e2dfae7f0c96b65d7862a938a55a4ed2bef8b743010632a5aee9ba0b38d0739852a944045fbcd3b84fb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
